name: benchmark

# This github action copied from https://github.com/phuslu/log/
# See license at https://github.com/phuslu/log/blob/master/LICENSE

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
      - name: Benchmark
        run: |
          curl -sL https://github.com/${GITHUB_REPOSITORY}/raw/master/README.md | \
          awk '{if($0 ~ "// go test -v"){a=1;b=1};if($0 ~ "```" && b=1){b=0};if (a&&b) {print}}' | \
          tee log_test.go
          export GOPROXY=direct
          go mod init main
          go get github.com/${GITHUB_REPOSITORY}@master
          go get github.com/phuslu/log
          go get github.com/francoispqt/onelog
          go get github.com/rs/zerolog
          go get go.uber.org/zap
          head -1 log_test.go | cut -b3- | sed -E 's#\r##' | bash -xe
